### ISSUE TITLE
Leaks in exit

### ISSUE THREAD

**Issue by Gotr-byte** [LukasKava/Minishell#43]
After entering minishell in minishell "exit 42" shows the following leak in fsanitize:

BiebianOS> exit 42
________CHUNK LIST_________________
full listC: indentifier: 21: (null)
ARGUMENTS:
exit 42 

AddressSanitizer:DEADLYSIGNAL
=================================================================
==4911==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x55a4f52937d8 bp 0x7fff741f63f0 sp 0x7fff741f63c0 T0)
==4911==The signal is caused by a READ memory access.
==4911==Hint: address points to the zero page.
    #0 0x55a4f52937d8 in builtins_exit src/builtins/exit.c:83
    #1 0x55a4f52998ab in exit_handle src/execute/builtin_handles.c:109
    #2 0x55a4f5296b27 in built_in_handler src/execute/new_fork.c:108
    #3 0x55a4f5296e2d in execute src/execute/new_fork.c:134
    #4 0x55a4f5283e47 in parsing_and_execution src/parsing/main.c:123
    #5 0x55a4f52840f6 in main src/parsing/main.c:155
    #6 0x7f36c8a17d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #7 0x7f36c8a17e3f in __libc_start_main_impl ../csu/libc-start.c:392
    #8 0x55a4f52835e4 in _start (/home/piotr/code/mini/minishell+0x45e4)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV src/builtins/exit.c:83 in builtins_exit
==4911==ABORTING

**Comment by LukasKava** [comment]
fixed the leak in exit
