### ISSUE TITLE
$>nonExistingFile.txt > ls | wc $>exit

### ISSUE THREAD

**Issue by Gotr-byte** [LukasKava/Minishell#48]
=================================================================
==3614==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 96 byte(s) in 1 object(s) allocated from:
    #0 0x7f8dcf2e5867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55c2ae2c65a4 in ft_split (/home/piotr/code/minish/minishell+0x1b5a4)
    #2 0x55c2ae2b3d1c in check_command_excists src/parsing/register_tokens.c:313
    #3 0x55c2ae2b44e9 in register_tokens src/parsing/register_tokens.c:378
    #4 0x55c2ae2afd27 in parsing_and_execution src/parsing/main.c:117
    #5 0x55c2ae2b00f6 in main src/parsing/main.c:155
    #6 0x7f8dcefded8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Indirect leak of 119 byte(s) in 10 object(s) allocated from:
    #0 0x7f8dcf2e5867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55c2ae2c64db in s_words (/home/piotr/code/minish/minishell+0x1b4db)
    #2 0x55c2ae2c65ce in ft_split (/home/piotr/code/minish/minishell+0x1b5ce)
    #3 0x55c2ae2b3d1c in check_command_excists src/parsing/register_tokens.c:313
    #4 0x55c2ae2b44e9 in register_tokens src/parsing/register_tokens.c:378
    #5 0x55c2ae2afd27 in parsing_and_execution src/parsing/main.c:117
    #6 0x55c2ae2b00f6 in main src/parsing/main.c:155
    #7 0x7f8dcefded8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f8dcf2e5867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55c2ae2c6062 in ft_calloc (/home/piotr/code/minish/minishell+0x1b062)
    #2 0x55c2ae2b39e5 in ft_delete src/parsing/register_tokens.c:274
    #3 0x55c2ae2b3d5a in check_command_excists src/parsing/register_tokens.c:314
    #4 0x55c2ae2b44e9 in register_tokens src/parsing/register_tokens.c:378
    #5 0x55c2ae2afd27 in parsing_and_execution src/parsing/main.c:117
    #6 0x55c2ae2b00f6 in main src/parsing/main.c:155
    #7 0x7f8dcefded8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: 231 byte(s) leaked in 12 allocation(s).

**Comment by LukasKava** [comment]
fixed the issue
