### ISSUE TITLE
$>pwd $>unset PWD $>env | grep PWD

### ISSUE THREAD

**Issue by Gotr-byte** [LukasKava/Minishell#49]
=================================================================
==7850==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 96 byte(s) in 1 object(s) allocated from:
    #0 0x7ff6f279b867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55e4b4c36561 in ft_split (/home/piotr/code/minish/minishell+0x1b561)
    #2 0x55e4b4c2850a in find_command_path src/parsing/parsing.c:44
    #3 0x55e4b4c295a1 in get_the_commands src/parsing/parsing.c:204
    #4 0x55e4b4c1fd96 in parsing_and_execution src/parsing/main.c:119
    #5 0x55e4b4c200f6 in main src/parsing/main.c:155
    #6 0x7ff6f2494d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 96 byte(s) in 1 object(s) allocated from:
    #0 0x7ff6f279b867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55e4b4c36561 in ft_split (/home/piotr/code/minish/minishell+0x1b561)
    #2 0x55e4b4c23d1c in check_command_excists src/parsing/register_tokens.c:313
    #3 0x55e4b4c244e9 in register_tokens src/parsing/register_tokens.c:378
    #4 0x55e4b4c1fd27 in parsing_and_execution src/parsing/main.c:117
    #5 0x55e4b4c200f6 in main src/parsing/main.c:155
    #6 0x7ff6f2494d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 6 byte(s) in 1 object(s) allocated from:
    #0 0x7ff6f279b867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55e4b4c3601f in ft_calloc (/home/piotr/code/minish/minishell+0x1b01f)
    #2 0x55e4b4c2d9c9 in save_name src/builtins/builtins_utils.c:121
    #3 0x55e4b4c31a00 in delete_env_node src/builtins/unset.c:64
    #4 0x55e4b4c320ea in builtins_unset src/builtins/unset.c:130
    #5 0x55e4b4c35796 in unset_handle src/execute/builtin_handles.c:95
    #6 0x55e4b4c32b18 in built_in_handler src/execute/new_fork.c:99
    #7 0x55e4b4c32e20 in execute src/execute/new_fork.c:126
    #8 0x55e4b4c1fe47 in parsing_and_execution src/parsing/main.c:123
    #9 0x55e4b4c200f6 in main src/parsing/main.c:155
    #10 0x7ff6f2494d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Indirect leak of 190 byte(s) in 11 object(s) allocated from:
    #0 0x7ff6f279b867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55e4b4c36680 in ft_strjoin (/home/piotr/code/minish/minishell+0x1b680)
    #2 0x55e4b4c23eb0 in check_command_excists src/parsing/register_tokens.c:318
    #3 0x55e4b4c244e9 in register_tokens src/parsing/register_tokens.c:378
    #4 0x55e4b4c1fd27 in parsing_and_execution src/parsing/main.c:117
    #5 0x55e4b4c200f6 in main src/parsing/main.c:155
    #6 0x7ff6f2494d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: 388 byte(s) leaked in 14 allocation(s).
OLDPWD=/home/piotr/code/minish

**Comment by LukasKava** [comment]
cleaned up and got ridd the leaks
