### ISSUE TITLE
crashes when enetering to the shell the following: &&

### ISSUE THREAD

**Issue by Gotr-byte** [LukasKava/Minishell#76]
Juno> &&
AddressSanitizer:DEADLYSIGNAL
=================================================================
==17498==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x55bbee08ee2d bp 0x7ffccae21bc0 sp 0x7ffccae21ba0 T0)
==17498==The signal is caused by a READ memory access.
==17498==Hint: address points to the zero page.
    #0 0x55bbee08ee2d in exit_status src/parsing/expansions.c:70
    #1 0x55bbee08f09f in expand_expansions src/parsing/expansions.c:89
    #2 0x55bbee087b02 in register_tokens src/parsing/register_tokens.c:180
    #3 0x55bbee084bce in parsing_and_execution src/parsing/main.c:89
    #4 0x55bbee085004 in main src/parsing/main.c:121
    #5 0x7fe16dd12d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #6 0x7fe16dd12e3f in __libc_start_main_impl ../csu/libc-start.c:392
    #7 0x55bbee084624 in _start (/home/piotr/code/mini_v8/minishell+0x4624)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV src/parsing/expansions.c:70 in exit_status
==17498==ABORTING

**Comment by Gotr-byte** [comment]
Also crashes when &&&&&.

**Comment by LukasKava** [comment]
issue fixed
