### ISSUE TITLE
crashes when ;;

### ISSUE THREAD

**Issue by Gotr-byte** [LukasKava/Minishell#77]
Juno> ;;
AddressSanitizer:DEADLYSIGNAL
=================================================================
==18754==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x55d73b431da7 bp 0x7ffc98343630 sp 0x7ffc98343610 T0)
==18754==The signal is caused by a READ memory access.
==18754==Hint: address points to the zero page.
    #0 0x55d73b431da7 in exit_status src/parsing/expansions.c:70
    #1 0x55d73b432019 in expand_expansions src/parsing/expansions.c:89
    #2 0x55d73b42aa7c in register_tokens src/parsing/register_tokens.c:180
    #3 0x55d73b427bce in parsing_and_execution src/parsing/main.c:89
    #4 0x55d73b427f7e in main src/parsing/main.c:121
    #5 0x7f975ee03d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #6 0x7f975ee03e3f in __libc_start_main_impl ../csu/libc-start.c:392
    #7 0x55d73b427624 in _start (/home/piotr/code/mini_v8/minishell+0x4624)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV src/parsing/expansions.c:70 in exit_status
==18754==ABORTING

**Comment by LukasKava** [comment]
issue fixed!
